### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function Moxl\Stanza\Pubsub::create()

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#364]
```
[20-Mar-2017 15:00:21 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Moxl\Stanza\Pubsub::create(), 2 passed in /usr/share/webapps/movim/vendor/movim/moxl/src/Moxl/Xec/Action/Pubsub/TestCreate.php on line 17 and exactly 3 expected in /usr/share/webapps/movim/vendor/movim/moxl/src/Moxl/Stanza/Pubsub.php:7
Stack trace:
#0 /usr/share/webapps/movim/vendor/movim/moxl/src/Moxl/Xec/Action/Pubsub/TestCreate.php(17): Moxl\Stanza\Pubsub::create('pubsub.bouah.ne...', 'test_node')
#1 /usr/share/webapps/movim/app/widgets/CommunitiesServer/CommunitiesServer.php(88): Moxl\Xec\Action\Pubsub\TestCreate->request()
#2 [internal function]: CommunitiesServer->ajaxTestAdd('pubsub.bouah.ne...')
#3 /usr/share/webapps/movim/src/Movim/Widget/Wrapper.php(141): call_user_func_array(Array, Array)
#4 /usr/share/webapps/movim/src/Movim/RPC.php(90): Movim\Widget\Wrapper->runWidget('CommunitiesServ...', 'ajaxTestAdd', Array)
#5 /usr/share/webapps/movim/linker.php(173): Movim\RPC->handle_json(Object(stdClass))
#6 [internal function]: {closure}('{"func": in /usr/share/webapps/movim/vendor/movim/moxl/src/Moxl/Stanza/Pubsub.php on line 7
```

I just updated to 0.11. I am running prosody-trunk.
I get this error when I try to add a group on a pubsub server, and I then get redirected to the login page.

**Comment by ghost** [comment]
I get the same error since the update to 0.11. Now it'ts not possible to create any groups. :-(
I use ejabberd and configured it like proposed in the wiki.

**Comment by ghost** [comment]
I did an git pull and restarted the movim-daemon, but the error persists.

**Comment by ghost** [comment]
okay, sorry. I had to php composer.phar install, and then restart the daemon.
But now i get an notification that i cannot create a new Group... :(
